# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calcula.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calcula.proto',
  package='calcula',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcalcula.proto\x12\x07\x63\x61lcula\"@\n\x12\x46indNumbersRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x12\r\n\x05start\x18\x03 \x01(\x05\"/\n\x13\x46indNumbersResponse\x12\x0b\n\x03max\x18\x01 \x01(\x05\x12\x0b\n\x03min\x18\x02 \x01(\x05\x32Z\n\x0e\x43\x61lculaService\x12H\n\x0b\x46indNumbers\x12\x1b.calcula.FindNumbersRequest\x1a\x1c.calcula.FindNumbersResponseb\x06proto3'
)




_FINDNUMBERSREQUEST = _descriptor.Descriptor(
  name='FindNumbersRequest',
  full_name='calcula.FindNumbersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='calcula.FindNumbersRequest.vector', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='calcula.FindNumbersRequest.end', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='calcula.FindNumbersRequest.start', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=90,
)


_FINDNUMBERSRESPONSE = _descriptor.Descriptor(
  name='FindNumbersResponse',
  full_name='calcula.FindNumbersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max', full_name='calcula.FindNumbersResponse.max', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min', full_name='calcula.FindNumbersResponse.min', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['FindNumbersRequest'] = _FINDNUMBERSREQUEST
DESCRIPTOR.message_types_by_name['FindNumbersResponse'] = _FINDNUMBERSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FindNumbersRequest = _reflection.GeneratedProtocolMessageType('FindNumbersRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDNUMBERSREQUEST,
  '__module__' : 'calcula_pb2'
  # @@protoc_insertion_point(class_scope:calcula.FindNumbersRequest)
  })
_sym_db.RegisterMessage(FindNumbersRequest)

FindNumbersResponse = _reflection.GeneratedProtocolMessageType('FindNumbersResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINDNUMBERSRESPONSE,
  '__module__' : 'calcula_pb2'
  # @@protoc_insertion_point(class_scope:calcula.FindNumbersResponse)
  })
_sym_db.RegisterMessage(FindNumbersResponse)



_CALCULASERVICE = _descriptor.ServiceDescriptor(
  name='CalculaService',
  full_name='calcula.CalculaService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=141,
  serialized_end=231,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindNumbers',
    full_name='calcula.CalculaService.FindNumbers',
    index=0,
    containing_service=None,
    input_type=_FINDNUMBERSREQUEST,
    output_type=_FINDNUMBERSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULASERVICE)

DESCRIPTOR.services_by_name['CalculaService'] = _CALCULASERVICE

# @@protoc_insertion_point(module_scope)
